---
title: "Research Projects"
from: markdown+emoji
filters:
  - tables_filter.lua
---

::: {.column-body-outset}

|        | {{< fa globe >}} |{{< fa building-columns >}} \ Host| Project   | Supervisor   |
|:-----|----|:------|--------------------|-------------|
| **ESR1**  | {{< iconify openmoji flag-ireland size=2x >}} |  <a href=https://www.adaptcentre.ie>TCD</a>     | Scalable semantic data architecture for study of chronic disease                                                               | Declan O'Sullivan        |
| **ESR2**  | {{< iconify openmoji flag-switzerland size=2x >}}           |<a href=https://www.zurich.ibm.com/>IBM</a>        | Cross-Domain Data Fusion techniques for vasculitis prediction                                                                  | María Rodríguez-Martínez |
| **ESR3**  | {{< iconify openmoji flag-ireland size=2x >}}               |<a href=https://www.scss.tcd.ie/>TCD</a>           | Ensemble averaging for complex disease prediction in the large p small n domain from multiple data                             | Jason Wyse               |
| **ESR4**  | {{< iconify openmoji flag-united-kingdom size=2x >}}         |<a href=https://www.gla.ac.uk/>UGLAS</a>       | Harnessing the power of integrated data to investigate environmental exposures on ANCA vasculitis risk -- an unbiased approach | Neil Basu                |
| **ESR5**  | {{< iconify openmoji flag-switzerland size=2x >}}           |<a href=https://www.kssg.ch/>KSSG</a>              | Focused study of the environmental impact on development of ANCA vasculitis- a hypothesis driven approach                      | Alfred Mahr              |
| **ESR6**  | {{< iconify openmoji flag-spain size=2x >}}        |<a href=https://www.isglobal.org/>ISGlobal</a>          | Atmospheric monitoring and time series analysis of climate and pollution impact on vasculitis onset                            | Xavier Rodó              |
| **ESR7**  | {{< iconify openmoji flag-spain size=2x >}}        |<a href=www.ipb.csic.es>CSIC</a>                  | Identification of functionally relevant genetic variants associated with GCA                                                   | Javier Martin            |
| **ESR8**  | {{< iconify openmoji flag-united-kingdom size=2x >}}         |<a href=https://lida.leeds.ac.uk/target>ULEEDS</a> | Linking public and GCA datasets to identify novel pathogenic pathways                                                          | Ann Morgan               |
| **ESR9**  | {{< iconify openmoji flag-spain size=2x >}}       |<a href=https://www.anaxomics.com>AX</a>                    | Systems biology and bioinformatics approaches to provide a holistic understanding of GCA biology                               | José Manuel Mas          |
| **ESR10** | {{< iconify openmoji flag-spain size=2x >}}        |<a href=https://www.idibaps.org>IDIBAPS</a>                | Functional characterisation of inflammation and vascular remodelling pathways in GCA                                           | Maria Cid                |
| **ESR11** | {{< iconify openmoji flag-austria size=2x >}}               |<a href=https://www.meduniwien.ac.at>MUW</a>                | Extracellular Vesicles (EV) as markers of active disease in AAV                                                                | Renate Kain              |
| **ESR12** | {{< iconify openmoji flag-austria size=2x >}}               |<a href=https://www.tissuegnostics.com >TG</a>              | Computer assisted morphometry of pathological changes in renal biopsies from patients with AAV                                 | Rupert Ecker             |
| **ESR13** | {{< iconify openmoji flag-sweden size=2x >}}                     |<a href=https://www.kth.se>KTH</a>                         | Profiling the autoantibody repertoire in the context of systemic vasculitis flare                                              | Peter Nilsson            |
| **ESR14** | {{< iconify openmoji flag-france size=2x >}}                     |<a href=https://www.firalis.com>FI</a>                      | A novel multi-parametric diagnostic tool for diagnosis of vasculitis                                                           | Hueseyin Firat           |
| **ESR15** | {{< iconify openmoji flag-belgium size=2x >}}               |<a href=https://www.i-hd.eu>I-HD</a>  | Data management for promoting research while protecting privacy                                                                | Pascal Coorevits         | 
: {.table-striped.table-hover.hide-caption.table-responsive}
:::
